services:
    # Backend API
    facerecognitionbrain-api:
        container_name: backend
        build: ./
        command: npm start
        environment:
            POSTGRES_URI: postgres://someuser:somepassword@postgres:5432/smart-brain-docker
            REDIS_URI: redis://redis:6379
        links:
            - postgres
            - redis
        working_dir: /usr/src/facerecognition-api
        ports:
            - '3000:3000'
        volumes:
            - ./:/usr/src/facerecognition-api
    # PostgresDB
    postgres:
        environment:
            POSTGRES_USER: someuser
            POSTGRES_PASSWORD: somepassword
            POSTGRES_DB: smart-brain-docker
            POSTGRES_HOST: postgres
        build: ./postgres
        ports:
            - '5431:5432'

    # Redis
    redis:
        image: redis
        ports:
            - '6379:6379'
